name: Push to mirror

on:
    push:
    workflow_dispatch:

jobs:
    push_to_mirror:
        name: Push to mirror
        if: ${{ github.repository_owner == 'hugoschool' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
              with:
                fetch-depth: 0
            - name: Pushing to mirror repo
              uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url: ${{ secrets.MIRROR_URL }}
                ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
